name: CI
on:
  push:
    branches: [master, animation]
  pull_request:
    branches: [master, animation]
  workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Test
    if: github.event_name != 'pull_request' || github.event.pull_request.labels.*.name == 'preview'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Run Build
        run: npm run build

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Clean install
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Copy static files
        run: |
          mkdir -p site
          mkdir -p site/dist
          if [ -d "dist" ]; then cp -r dist/* site/dist/; else echo "dist directory does not exist"; fi
          if [ -f "index.html" ]; then cp index.html site/index.html; else echo "index.html file does not exist"; fi
      - name: Upload static files as artifact
        # This action uploads the static files to be used by the deploy-pages action for GitHub Pages deployment
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
        outputs:
          artifact_path: site
          artifact_name: static-files
          artifact_url: ${{ steps.deployment.outputs.artifact_url }}
      # This step deploys the static files to GitHub Pages using the artifact uploaded in the previous step.
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
